services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Stasenko2005
      POSTGRES_USER: Stasenko
      POSTGRES_DB: yugStroyInvest
    volumes:
      - main:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Stasenko -d yugStroyInvest" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G

volumes:
  main:
