"""empty message

Revision ID: 036401bc28bb
Revises: 5cabceed9370
Create Date: 2025-09-22 21:31:02.821879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036401bc28bb'
down_revision: Union[str, Sequence[str], None] = '5cabceed9370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_admin_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('companies_user_manager_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_admin_id'], ['id'])
    op.drop_column('companies', 'user_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_manager_id_fkey'), 'companies', 'users', ['user_manager_id'], ['id'])
    op.drop_column('companies', 'user_admin_id')
    # ### end Alembic commands ###
