"""empty message

Revision ID: 3cf6718613d4
Revises: b66e4c48335f
Create Date: 2025-09-26 21:21:28.887109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf6718613d4'
down_revision: Union[str, Sequence[str], None] = 'b66e4c48335f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_engineer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('companies_user_engineer_ids_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_engineer_id'], ['id'])
    op.drop_column('companies', 'user_engineer_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_engineer_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_engineer_ids_fkey'), 'companies', 'users', ['user_engineer_ids'], ['id'])
    op.drop_column('companies', 'user_engineer_id')
    # ### end Alembic commands ###
