"""empty message

Revision ID: 627e14c3a6ed
Revises: 032c47415096
Create Date: 2025-09-26 22:15:21.680005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627e14c3a6ed'
down_revision: Union[str, Sequence[str], None] = '032c47415096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_client_company_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_client_company_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'client_company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_client_company_id_fkey'), 'users', 'companies', ['client_company_id'], ['id'])
    op.create_unique_constraint(op.f('users_client_company_id_key'), 'users', ['client_company_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
