"""empty message

Revision ID: 7a7550f85e9b
Revises: d3fd8e4f01cc
Create Date: 2025-09-26 21:07:41.365092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7550f85e9b'
down_revision: Union[str, Sequence[str], None] = 'd3fd8e4f01cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_engineer_ids', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('companies_user_engineer_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_engineer_ids'], ['id'])
    op.drop_column('companies', 'user_engineer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_engineer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_engineer_id_fkey'), 'companies', 'users', ['user_engineer_id'], ['id'])
    op.drop_column('companies', 'user_engineer_ids')
    # ### end Alembic commands ###
