"""empty message

Revision ID: 91ff545ac885
Revises: e54f9c86f554
Create Date: 2025-09-24 01:11:32.658713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ff545ac885'
down_revision: Union[str, Sequence[str], None] = 'e54f9c86f554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('defects_project_id_fkey'), 'defects', type_='foreignkey')
    op.create_foreign_key(None, 'defects', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.create_foreign_key(op.f('defects_project_id_fkey'), 'defects', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
