"""empty message

Revision ID: 9dfa8d76b83c
Revises: 8d3a47217948
Create Date: 2025-09-24 01:28:57.434249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfa8d76b83c'
down_revision: Union[str, Sequence[str], None] = '8d3a47217948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_engineers_project_id_fkey'), 'projects_engineers', type_='foreignkey')
    op.create_foreign_key(None, 'projects_engineers', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects_engineers', type_='foreignkey')
    op.create_foreign_key(op.f('projects_engineers_project_id_fkey'), 'projects_engineers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
